services:
  server:
    build: ./server
    ports:
      - "5000:5000" # Expose server on port 5000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=5000
    env_file: .env

  client:
    build: ./client
    ports:
      - "4000:4000" # Expose client on port 4000
    depends_on:
      - server
    env_file: .env

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./server/backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "5434:5432" # PostgreSQL default port
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 10s
      retries: 30

volumes:
  db_data:
