services:
  server:
    build: ./server
    ports:
      - "5000:5000" # Expose server on port 5000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=5000
    env_file: .env
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    ports:
      - "4000:4000" # Expose client on port 4000
    depends_on:
      - server
    env_file: .env
    volumes:
      - ./client:/app
      - /app/node_modules

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./server/backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "3307:3306" # Expose database on port 3306
    healthcheck:
      # test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 10s
      retries: 30

volumes:
  db_data:
