services:
  database:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./server/backup.sql:/docker-entrypoint-initdb.d/backup.sql
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 10s
      retries: 30

  backend:
    build: ./server
    container_name: python-backend
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    restart: always

  frontend:
    build: ./client
    container_name: react-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: always

volumes:
  mysql-data:
