services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: node server/index.js
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app/server
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

  client:
    build:
      context: .
      dockerfile: Dockerfile
    command: serve -s -l 5000 client/dist
    ports:
      - "5000:5000"
    volumes:
      - ./client:/app/client
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./server/backup.sql:/docker-entrypoint-initdb.d/backup.sql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 30

volumes:
  mysql-data:
