import BuildIcon from "@mui/icons-material/Build";
import RecordVoiceOverIcon from "@mui/icons-material/RecordVoiceOver";
import TipsAndUpdatesIcon from "@mui/icons-material/TipsAndUpdates";
import {
  Box,
  Card,
  CardActionArea,
  CardContent,
  Dialog,
  DialogContent,
  DialogTitle,
  Grid,
  Typography,
  useTheme,
} from "@mui/material";
import React, { useState } from "react";

type Tool = {
  name: string;
  description: string;
  icon: React.ReactNode;
  content: React.ReactNode;
};

const tools: Tool[] = [
  {
    name: "Audio Reporter",
    description: "Report incidents using your voice",
    icon: <RecordVoiceOverIcon color="primary" fontSize="large" />,
    content: <Typography>Audio reporting tool will go here.</Typography>,
  },
  {
    name: "Safety Tips",
    description: "Get safety recommendations generated by AI",
    icon: <TipsAndUpdatesIcon color="warning" fontSize="large" />,
    content: <Typography>Safety tips tool content goes here.</Typography>,
  },
  {
    name: "Settings",
    description: "Customize your app experience",
    icon: <BuildIcon color="secondary" fontSize="large" />,
    content: <Typography>Settings tool content goes here.</Typography>,
  },
];

const ToolsPage: React.FC = () => {
  const theme = useTheme();
  const [openTool, setOpenTool] = useState<Tool | null>(null);

  return (
    <Box sx={{ mt: 4, px: 2 }}>
      <Typography variant="h4" gutterBottom>
        🧰 Available Tools
      </Typography>

      <Grid container spacing={3} mt={3}>
        {tools.map((tool) => (
          <Grid key={tool.name} size={{ xs: 12, sm: 6, md: 4 }}>
            <Card
              sx={{
                p: 2,
                display: "flex",
                alignItems: "center",
                gap: 2,
                borderLeft: `6px solid ${theme.palette.primary.main}`,
                height: "100%",
              }}
            >
              <CardActionArea onClick={() => setOpenTool(tool)}>
                <Box display="flex" alignItems="center" gap={2}>
                  {tool.icon}
                  <CardContent sx={{ padding: 0 }}>
                    <Typography variant="h6">{tool.name}</Typography>
                    <Typography variant="body2" color="text.secondary">
                      {tool.description}
                    </Typography>
                  </CardContent>
                </Box>
              </CardActionArea>
            </Card>
          </Grid>
        ))}
      </Grid>

      <Dialog
        open={Boolean(openTool)}
        onClose={() => setOpenTool(null)}
        fullWidth
        maxWidth="sm"
      >
        <DialogTitle>{openTool?.name}</DialogTitle>
        <DialogContent>{openTool?.content}</DialogContent>
      </Dialog>
    </Box>
  );
};

export default ToolsPage;
